services:
  db:
    image: postgres
    restart: always
    container_name: pg-bank-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      retries: 5
  app:
    container_name: bank-service
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
